import { NextRequest, NextResponse } from "next/server";
import { getProfileById } from "@/lib/profiles";
import JSZip from "jszip";

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const profileId = searchParams.get('id');

    if (!profileId) {
      return NextResponse.json({ error: 'Profile ID is required' }, { status: 400 });
    }

    const profile = getProfileById(profileId);
    if (!profile) {
      return NextResponse.json({ error: 'Profile not found' }, { status: 404 });
    }

    // Generate static HTML content
    const htmlContent = generateStaticHTML(profile, profileId);
    
    // Generate CSS content
    const cssContent = generateStaticCSS();

    // Create ZIP file
    const zip = new JSZip();
    zip.file("index.html", htmlContent);
    zip.file("style.css", cssContent);
    
    // Add a README file
    const readmeContent = `# ${profile.name} - Portfolio

This is a static portfolio website generated by GoRoFolio.

## Files:
- index.html - The main portfolio page
- style.css - Styling for the portfolio
- README.md - This file

## Usage:
1. Open index.html in a web browser
2. The portfolio will display all sections including experience, education, and skills
3. All styles are contained in the CSS file for easy customization

Generated on: ${new Date().toISOString()}
`;
    
    zip.file("README.md", readmeContent);

    // Generate ZIP buffer
    const zipBuffer = await zip.generateAsync({ type: "nodebuffer" });

    // Return ZIP file
    return new NextResponse(zipBuffer, {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="portfolio-${profileId}.zip"`,
      },
    });

  } catch (error) {
    console.error('Export error:', error);
    return NextResponse.json({ 
      error: 'Failed to export portfolio', 
      details: error instanceof Error ? error.message : 'Unknown error' 
    }, { status: 500 });
  }
}

function generateStaticHTML(profile: any, profileId: string): string {
  const formatDate = (dateStr: string | undefined) => {
    if (!dateStr) return "Present";
    const [year, month] = dateStr.split('-');
    const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    return `${monthNames[parseInt(month) - 1]} ${year}`;
  };

  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${profile.name} - Portfolio</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="container">
        <!-- Header -->
        <header class="header">
            <div class="profile-photo">
                <span class="initials">${profile.name.split(' ').map((n: string) => n[0]).join('')}</span>
            </div>
            <h1 class="name">${profile.name}</h1>
            <h2 class="headline">${profile.headline}</h2>
        </header>

        <!-- External Links -->
        ${profile.links && profile.links.length > 0 ? `
        <section class="links-section">
            <h3>External Links</h3>
            <div class="links-container">
                ${profile.links.map((link: any) => `
                    <a href="${link.url}" target="_blank" rel="noopener noreferrer" class="link-item">
                        ${link.label}
                    </a>
                `).join('')}
            </div>
        </section>
        ` : ''}

        <!-- Summary -->
        <section class="section">
            <h2>Summary</h2>
            <p class="summary">${profile.summary}</p>
        </section>

        <!-- Experience -->
        <section class="section">
            <h2>Experience</h2>
            ${profile.experiences.map((exp: any) => `
                <div class="experience-item">
                    <div class="experience-header">
                        <div>
                            <h3 class="role">${exp.role}</h3>
                            <h4 class="company">${exp.company}</h4>
                        </div>
                        <div class="date">${formatDate(exp.start)} - ${formatDate(exp.end)}</div>
                    </div>
                    <ul class="bullets">
                        ${exp.bullets.map((bullet: string) => `<li>${bullet}</li>`).join('')}
                    </ul>
                </div>
            `).join('')}
        </section>

        <!-- Education -->
        <section class="section">
            <h2>Education</h2>
            ${profile.education.map((edu: any) => `
                <div class="education-item">
                    <div class="education-header">
                        <div>
                            <h3 class="degree">${edu.degree}</h3>
                            <h4 class="school">${edu.school}</h4>
                        </div>
                        <div class="year">${edu.year}</div>
                    </div>
                </div>
            `).join('')}
        </section>

        <!-- Skills -->
        <section class="section">
            <h2>Skills</h2>
            <div class="skills-container">
                ${profile.skills.map((skill: string) => `<span class="skill-tag">${skill}</span>`).join('')}
            </div>
        </section>
    </div>
</body>
</html>`;
}

function generateStaticCSS(): string {
  return `
/* Reset and Base Styles */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    line-height: 1.6;
    color: #374151;
    background: #f9fafb;
}

.container {
    max-width: 800px;
    margin: 0 auto;
    padding: 2rem;
    background: white;
    min-height: 100vh;
}

/* Header Styles */
.header {
    text-align: center;
    margin-bottom: 3rem;
    padding-bottom: 2rem;
    border-bottom: 2px solid #e5e7eb;
}

.profile-photo {
    width: 120px;
    height: 120px;
    margin: 0 auto 1.5rem;
    background: linear-gradient(135deg, #3b82f6, #8b5cf6);
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
}

.initials {
    font-size: 2rem;
    font-weight: bold;
    color: white;
}

.name {
    font-size: 2.5rem;
    font-weight: bold;
    color: #111827;
    margin-bottom: 0.5rem;
}

.headline {
    font-size: 1.25rem;
    color: #6b7280;
    font-weight: 500;
}

/* Section Styles */
.section {
    margin-bottom: 2.5rem;
}

.section h2 {
    font-size: 1.5rem;
    font-weight: bold;
    color: #111827;
    margin-bottom: 1rem;
    padding-bottom: 0.5rem;
    border-bottom: 2px solid #3b82f6;
}

.summary {
    font-size: 1rem;
    line-height: 1.7;
    text-align: justify;
}

/* Links Section */
.links-section {
    margin-bottom: 2rem;
}

.links-section h3 {
    font-size: 1.125rem;
    font-weight: 600;
    color: #374151;
    margin-bottom: 1rem;
}

.links-container {
    display: flex;
    flex-wrap: wrap;
    gap: 0.75rem;
}

.link-item {
    display: inline-block;
    padding: 0.5rem 1rem;
    background: linear-gradient(135deg, #dbeafe, #ede9fe);
    color: #1d4ed8;
    text-decoration: none;
    border-radius: 0.75rem;
    border: 1px solid #bfdbfe;
    font-weight: 500;
    transition: all 0.2s ease;
}

.link-item:hover {
    background: linear-gradient(135deg, #bfdbfe, #ddd6fe);
    transform: translateY(-1px);
}

/* Experience Styles */
.experience-item {
    background: linear-gradient(135deg, #f0f9ff, #faf5ff);
    padding: 1.5rem;
    border-radius: 0.75rem;
    border: 1px solid #e0e7ff;
    margin-bottom: 1.5rem;
}

.experience-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    margin-bottom: 1rem;
}

.role {
    font-size: 1.125rem;
    font-weight: bold;
    color: #111827;
}

.company {
    font-size: 1rem;
    font-weight: 600;
    color: #2563eb;
    margin-top: 0.25rem;
}

.date {
    color: #6b7280;
    font-weight: 500;
    font-size: 0.875rem;
}

.bullets {
    list-style: none;
    margin-left: 0;
}

.bullets li {
    position: relative;
    margin-bottom: 0.5rem;
    padding-left: 1.5rem;
}

.bullets li:before {
    content: '•';
    color: #3b82f6;
    font-weight: bold;
    position: absolute;
    left: 0;
}

/* Education Styles */
.education-item {
    background: linear-gradient(135deg, #f0f9ff, #faf5ff);
    padding: 1.5rem;
    border-radius: 0.75rem;
    border: 1px solid #e0e7ff;
    margin-bottom: 1rem;
}

.education-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
}

.degree {
    font-size: 1rem;
    font-weight: bold;
    color: #111827;
}

.school {
    font-size: 0.875rem;
    font-weight: 600;
    color: #2563eb;
    margin-top: 0.25rem;
}

.year {
    color: #6b7280;
    font-weight: 500;
    font-size: 0.875rem;
}

/* Skills Styles */
.skills-container {
    display: flex;
    flex-wrap: wrap;
    gap: 0.75rem;
}

.skill-tag {
    padding: 0.5rem 1rem;
    background: linear-gradient(135deg, #dbeafe, #ede9fe);
    color: #1e40af;
    border-radius: 9999px;
    border: 1px solid #bfdbfe;
    font-weight: 500;
    font-size: 0.875rem;
}

/* Print Styles */
@media print {
    body {
        background: white;
    }
    
    .container {
        padding: 0;
        box-shadow: none;
    }
    
    .links-section {
        display: none;
    }
}

/* Responsive Design */
@media (max-width: 640px) {
    .container {
        padding: 1rem;
    }
    
    .name {
        font-size: 2rem;
    }
    
    .experience-header,
    .education-header {
        flex-direction: column;
        align-items: flex-start;
    }
    
    .date,
    .year {
        margin-top: 0.5rem;
    }
}
`;
} 